package lt.mif.vu.mybatis.dao;

import lt.mif.vu.mybatis.model.Project;

import java.util.List;

public interface ProjectMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    int insert(Project record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    Project selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    List<Project> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    int updateByPrimaryKey(Project record);
}