package lt.mif.vu.mybatis.dao;

import lt.mif.vu.mybatis.model.ProjectUser;

import java.util.List;

public interface ProjectUserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT_USER
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    int insert(ProjectUser record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.PROJECT_USER
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    List<ProjectUser> selectAll();
}