package lt.mif.vu.mybatis.model;

public class Bug {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUG.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUG.TITLE
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.BUG.PROJECT_ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    private Integer projectId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUG.ID
     *
     * @return the value of PUBLIC.BUG.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUG.ID
     *
     * @param id the value for PUBLIC.BUG.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUG.TITLE
     *
     * @return the value of PUBLIC.BUG.TITLE
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUG.TITLE
     *
     * @param title the value for PUBLIC.BUG.TITLE
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.BUG.PROJECT_ID
     *
     * @return the value of PUBLIC.BUG.PROJECT_ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.BUG.PROJECT_ID
     *
     * @param projectId the value for PUBLIC.BUG.PROJECT_ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }
}