package lt.mif.vu.mybatis.model;

public class Project {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.ID
     *
     * @return the value of PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.ID
     *
     * @param id the value for PUBLIC.PROJECT.ID
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT.NAME
     *
     * @return the value of PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT.NAME
     *
     * @param name the value for PUBLIC.PROJECT.NAME
     *
     * @mbg.generated Sun Apr 19 22:08:27 EEST 2020
     */
    public void setName(String name) {
        this.name = name;
    }
}