package lt.mif.vu.mybatis.model;

public class ProjectUser {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT_USER.PROJECT_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    private Integer projectId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.PROJECT_USER.USERS_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    private Integer usersId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT_USER.PROJECT_ID
     *
     * @return the value of PUBLIC.PROJECT_USER.PROJECT_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    public Integer getProjectId() {
        return projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT_USER.PROJECT_ID
     *
     * @param projectId the value for PUBLIC.PROJECT_USER.PROJECT_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    public void setProjectId(Integer projectId) {
        this.projectId = projectId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.PROJECT_USER.USERS_ID
     *
     * @return the value of PUBLIC.PROJECT_USER.USERS_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    public Integer getUsersId() {
        return usersId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.PROJECT_USER.USERS_ID
     *
     * @param usersId the value for PUBLIC.PROJECT_USER.USERS_ID
     *
     * @mbg.generated Tue Apr 21 14:58:07 EEST 2020
     */
    public void setUsersId(Integer usersId) {
        this.usersId = usersId;
    }
}